language: python

python: 2.7

addons:
  postgresql: "9.3"

before_install:
  - psql -c 'create database art-reports;' -U postgres
  
install:
  - pip install -r requirements/requirements-dev.txt
  - python manage.py syncdb --noinput
  - python manage.py migrate


script:
  - manage.py test


notifications:
  email:
    on_success: change
    on_failure: change