language: python

python: 2.7

cache: pip

addons:
  postgresql: "9.3"

env:
  global:
    - DJANGO_SETTINGS_MODULE=crayonbox.settings.travis
    - COMPARE_SCRIPT=/bin/cat

before_install:
  - psql -d template1 -c 'create extension hstore;' -U postgres
  - psql -c 'create database "art-reports";' -U postgres

install:
  - pip install -r requirements-dev.txt
  - "mkdir -p ext && git clone https://android-review.linaro.org/linaro/art-testing ext/art-testing"

script:
  - python manage.py test --noinput -v 2
  - flake8 --select=F821,F823 . --exclude=.svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.virtualenv,ext


notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    - "chat.freenode.net#linaro-qa"
