language: python

python: 2.7

addons:
  postgresql: "9.3"

services:
  - redis-server
  
env:
- DJANGO_SETTINGS_MODULE=crayonbox.settings.travis

before_install:
  - psql -c 'create database "art-reports";' -U postgres
  
install:
  - pip install -r requirements-dev.txt

script:
  - python manage.py test --noinput -v 2


notifications:
  email:
    on_success: change
    on_failure: change