- name: rabbitmq install
  apt: pkg=rabbitmq-server state=installed update-cache=yes
  tags:
    - install
    - update

- name: rabbitmq vhost
  shell: rabbitmqctl add_vhost {{hostname}} || true
  register: vhost
  changed_when: '"vhost_already_exists" not in vhost.stderr'

- name: rabbitmq vhost permissions
  shell: rabbitmqctl set_permissions -p {{hostname}} guest ".*" ".*" ".*"
