---
- name: Install required system packages
  apt: pkg={{item}} state=installed update-cache=yes
  with_items:
    - git
    - apache2
    - libapache2-mod-wsgi
    - python-dev
    - python-pip
    - python-virtualenv
  tags:
    - install
    - update


- name: Upgrade PIP manager
  pip: name=pip extra_args="-U"
  pip: name=virtualenv extra_args="-U"

  tags:
    - install
    - update


- name: Create base directory for installation
  file: path={{install_base}}/{{hostname}}
        owner={{apache_user}}
        group={{apache_user}}
        mode=0755
        state=directory
  tags:
    - install

- name: Checkout application code
  # NOTE: we can't use "accept_hostkey=yes" because the user we clone as
  # will likely not have a proper .ssh directory. We instead use ssh_opts
  git: repo={{git_repo}}
       dest={{install_base}}/{{hostname}}/project
       version={{git_tag}}
       update=yes
       ssh_opts="-o StrictHostKeyChecking=no"
  sudo_user: "{{apache_user}}"
  notify: restart-apache
  tags:
    - install
    - update
    - django

- name: Install required application packages
  sudo_user: "{{apache_user}}"
  pip: >
    requirements={{install_base}}/{{hostname}}/project/requirements.txt
    virtualenv={{install_base}}/{{hostname}}/.virtualenv
  tags:
    - install
    - update

- name: Copy local settings
  sudo_user: "{{apache_user}}"
  when: django_local_settings is defined
  template: src={{django_local_settings}}
            dest={{django_app_root}}/local_settings.py
            owner={{apache_user}} group={{apache_user}} mode=0755
  notify: restart-apache
  tags:
    - install
    - update
    - django

- name: Run syncdb command
  sudo_user: "{{apache_user}}"
  command: "{{install_base}}/{{hostname}}/.virtualenv/bin/python {{django_app_root}}/manage.py syncdb --settings={{django_settings}} --noinput"
  tags:
    - update
    - django

- name: Run migrations (if installed)
  sudo_user: "{{apache_user}}"
  command: "{{install_base}}/{{hostname}}/.virtualenv/bin/python {{django_app_root}}/manage.py syncdb --settings={{django_settings}} --noinput"
  tags:
    - django
    - update

- name: Enable mod_wsgi
  command:  a2enmod {{ item }}
            creates=/etc/apache2/mods-enabled/{{ item }}.load
  with_items: apache_modules
  notify: restart-apache
  tags:
    - install
