---
- name: Configure art-reports.linaro.org
  hosts: all
  sudo: yes
  vars_files:
    - "secrets/{{inventory_hostname}}"
  roles:
  - postgres
  - art-reports-deps
  - django
  - art-reports-populate
  - celeryd
  - {role: apache-site, src: "art-reports.linaro.org", config: "{{inventory_hostname}}", tags: [apache] }
