---
- name: Configure art-reports.linaro.org
  hosts: all
  sudo: yes
  vars_files:
    - "secrets/art-reports-bot.key.yml"
    - "secrets/{{inventory_hostname}}"

  roles:
  - base
  - ssl
  - postgres
  - rabbitmq
  - django
  - celeryd
  - apache-site
