---
- name: Configure art-reports.linaro.org
  hosts: all
  sudo: yes
  vars_files:
    - "secrets/{{inventory_hostname}}"

  roles:
  - base
  - postgres
  - django
  - art-reports-populate
  - redis
  - celeryd
  - apache-site
